### ISSUE TITLE
Feature request: Configure paths for storing parts of ngrx when separateDirectory is true

### ISSUE THREAD

**Issue by talamaska** [NetanelBasal/ngrx-generator#1]
It's a great generator. Saves me whole bunch of time of writing those manually, I even hooked up an npm command in order not to install it globally. I have one feature request though. Would it be possible to configure paths via package.json where the files should be added. For example my structure requires to put actions, effects in ./app/shared/effects, ./app/shared/actions etc.

Regards

**Comment by NetanelBasal** [comment]
I will try to add this feature soon. Thanks!

**Comment by NetanelBasal** [comment]
Done! You can now add this:
``` js
 "ngrxGen": {
    "seperateDirectory": "true",
    "basePath": "./src/app/shared"
  }
```

Note that the path should be relative to your root `package.json`.

**Comment by talamaska** [comment]
Thank you very much

**Comment by otari** [comment]
Adding this configuration to the package.json gives an error saying:  
`res = path.slice(lastSlash + 1, i); 
RangeError: Maximum call stack size exceeded
`
