### ISSUE TITLE
Maximum call stack size exceeded error when run ngrx-gen

### ISSUE THREAD

**Issue by ngohungphuc** [NetanelBasal/ngrx-generator#8]
![image](https://user-images.githubusercontent.com/13591213/32364240-4ff7efa0-c0a6-11e7-86ae-cf84c4d121fd.png)

**Comment by NetanelBasal** [comment]
Can you provide more details? Like your environment? Versions?

**Comment by ngohungphuc** [comment]
My node version is 8.8.1

**Comment by NetanelBasal** [comment]
I tested it now with 8.8.1, and it works fine.

**Comment by NetanelBasal** [comment]
You can test if this is your problem, https://github.com/3rd-Eden/find-package-json/pull/2/files?

**Comment by danielsuter** [comment]
I've got the same issue in Win 10, with node 8.9.1.

The problem disappears, if I remove the slashes in the config.

**Comment by NetanelBasal** [comment]
Which slashes are you referring too?
